In [1]:
from FS_dangjin_pkg.config import *
import FS_dangjin_pkg.sales as S
import FS_dangjin_pkg.cost as C
import FS_dangjin_pkg.loan as L

In [4]:
import importlib
importlib.reload(S)
importlib.reload(C)
importlib.reload(L)

<module 'FS_dangjin_pkg.loan' from '/Users/KP_Hong/Documents/PyPrjt/[lib]DangjinLogistic/FS_dangjin_pkg/loan.py'>

In [5]:
#### Input Basic Data ####
mtrt = 10

#### Input Sales Data ####
pmnt_scd = [0, 3, 7, 10]
pmnt_rate = [0.1, 0.2, 0.2, 0.5]
sales_dct = {}

#물류시설용지
sales_lgstc = S.sales(title = '물류시설용지', aream2 = 244_377, unitprcm2 = 1.400/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '물류단지시설', sep2 = '물류시설', note = "")
sales_dct['sales_lgstc'] = sales_lgstc

#상류시설용지
sales_cmrcl = S.sales(title = '상류시설용지', aream2 = 34_926, unitprcm2 = 3.500/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '물류단지시설', sep2 = '상류시설', note = "")
sales_dct['sales_cmrcl'] = sales_cmrcl
                 
#단독주택용지
sales_house = S.sales(title = '단독주택용지', aream2 = 9_137, unitprcm2 = 2.830/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '지원시설', sep2 = '단독주택', note = "")
sales_dct['sales_house'] = sales_house
                 
#공동주택용지
sales_aptmt = S.sales(title = '공동주택용지', aream2 = 33_134, unitprcm2 = 4.100/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '지원시설', sep2 = '공동주택', note = "")
sales_dct['sales_aptmt'] = sales_aptmt
                 
#상업시설용지
sales_rtl = S.sales(title = '상업시설용지', aream2 = 17_195, unitprcm2 = 4.100/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '지원시설', sep2 = '상업시설', note = "")
sales_dct['sales_rtl'] = sales_rtl
                 
#업무시설용지
sales_ofc = S.sales(title = '업무시설용지', aream2 = 6_151, unitprcm2 = 4.350/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '지원시설', sep2 = '업무시설', note = "")
sales_dct['sales_ofc'] = sales_ofc
                 
#주차장
sales_prklt = S.sales(title = '주차장', aream2 = 8_352, unitprcm2 = 1.950/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '지원시설', sep2 = '주차장', note = "")
sales_dct['sales_prklt'] = sales_prklt
                 
#주유소
sales_gsstn = S.sales(title = '주유소', aream2 = 2_400, unitprcm2 = 4.100/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '지원시설', sep2 = '주유소', note = "")
sales_dct['sales_gsstn'] = sales_gsstn
                 
#자원순환시설
sales_rcclng = S.sales(title = '자원순환시설', aream2 = 10_000, unitprcm2 = 2.800/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '지원시설', sep2 = '자원순환시설', note = "")
sales_dct['sales_rcclng'] = sales_rcclng
                 
#발전시설
sales_pwrplnt = S.sales(title = '발전시설', aream2 = 10_000, unitprcm2 = 2.800/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '지원시설', sep2 = '발전시설', note = "")
sales_dct['sales_pwrplnt'] = sales_pwrplnt
                 
#가스정압기
sales_gsprs = S.sales(title = '가스정압기', aream2 = 25, unitprcm2 = 1.440/py, unitmtpl = pmnt_rate, inptidx = pmnt_scd, mtrt = mtrt,
                     sep1 = '공공시설', sep2 = '가스정압기', note = "")
sales_dct['sales_gsprs'] = sales_gsprs

#Merge
sales = S.salesmerge(sales_dct)

In [3]:
sales.df()

sales_lgstc   sales_cmrcl  sales_house   sales_aptmt     sales_rtl  \
-1       0.000000      0.000000     0.000000      0.000000      0.000000   
 0   10349.366338   3697.790389   782.195757   4109.444504   2132.609955   
 1       0.000000      0.000000     0.000000      0.000000      0.000000   
 2       0.000000      0.000000     0.000000      0.000000      0.000000   
 3   20698.732676   7395.580777  1564.391514   8218.889008   4265.219910   
 4       0.000000      0.000000     0.000000      0.000000      0.000000   
 5       0.000000      0.000000     0.000000      0.000000      0.000000   
 6       0.000000      0.000000     0.000000      0.000000      0.000000   
 7   20698.732676   7395.580777  1564.391514   8218.889008   4265.219910   
 8       0.000000      0.000000     0.000000      0.000000      0.000000   
 9       0.000000      0.000000     0.000000      0.000000      0.000000   
 10  51746.831691  18488.951943  3910.978784  20547.222521  10663.049775   

       sales_ofc  sales_prklt  sales_gsstn  sales_rcclng  sales_pwrplnt  \
-1      0.000000     0.000000     0.000000      0.000000       0.000000   
 0    809.394743   492.663618   297.660011    847.000032     847.000032   
 1      0.000000     0.000000     0.000000      0.000000       0.000000   
 2      0.000000     0.000000     0.000000      0.000000       0.000000   
 3   1618.789486   985.327237   595.320022   1694.000064    1694.000064   
 4      0.000000     0.000000     0.000000      0.000000       0.000000   
 5      0.000000     0.000000     0.000000      0.000000       0.000000   
 6      0.000000     0.000000     0.000000      0.000000       0.000000   
 7   1618.789486   985.327237   595.320022   1694.000064    1694.000064   
 8      0.000000     0.000000     0.000000      0.000000       0.000000   
 9      0.000000     0.000000     0.000000      0.000000       0.000000   
 10  4046.973714  2463.318092  1488.300056   4235.000159    4235.000159   

     sales_gsprs  
-1         0.000  
 0         1.089  
 1         0.000  
 2         0.000  
 3         2.178  
 4         0.000  
 5         0.000  
 6         0.000  
 7         2.178  
 8         0.000  
 9         0.000  
 10        5.445

In [8]:
sum(sales.amt())

243662.14378733034

In [15]:
prcs_rate = pd.Series([0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1], index=[1,2,3,4,5,6,7,8,9,10])

In [16]:
prcs_rate.index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [20]:
prcs_rate.values

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [19]:
dir(prcs_rate)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__

In [21]:
mthly = [np.ones(mtrt), np.arange(1, mtrt + 1)]

In [22]:
mthly

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])]

In [30]:
mthly = pd.Series(np.ones(mtrt), index=np.arange(1, mtrt+1))

In [31]:
mthly

1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
dtype: float64

In [24]:
prcs_rate = pd.Series({'data':[0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]}, index=[1,2,3,4,5,6,7,8,9,10])

In [26]:
prcs_rate.data

AttributeError: 'Series' object has no attribute 'data'

In [32]:
a = 21_398

In [42]:
np.ceil(a, -3)

TypeError: return arrays must be of ArrayType

In [36]:
k = 1_000

In [39]:
round(a/k,0) * k

21000.0

In [44]:
np.ceil(a/k) * k

22000.0

In [45]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
if 1 <= 4 and 3 <= 9:
    print('a')

a


In [50]:
import FS_dangjin_pkg.loan as L

In [51]:
TrA = L.loan(amt = 10000000, mtrt = 10, IR=0.05)

In [52]:
TrA.df

amt_ntnl  amt_paid  amt_paid_cum  amt_paid_rsdl  amt_repd  amt_repd_cum  \
-1   10000000         0             0       10000000         0             0   
 0   10000000         0             0       10000000         0             0   
 1   10000000         0             0       10000000         0             0   
 2   10000000         0             0       10000000         0             0   
 3   10000000         0             0       10000000         0             0   
 4   10000000         0             0       10000000         0             0   
 5   10000000         0             0       10000000         0             0   
 6   10000000         0             0       10000000         0             0   
 7   10000000         0             0       10000000         0             0   
 8   10000000         0             0       10000000         0             0   
 9   10000000         0             0       10000000         0             0   
 10  10000000         0             0       10000000         0             0   

     amt_rsdl  amt_paid_forIR  IR_rate  IR_amt  IR_amt_cum  IR_repd  \
-1          0               0     0.05     0.0         0.0        0   
 0          0               0     0.05     0.0         0.0        0   
 1          0               0     0.05     0.0         0.0        0   
 2          0               0     0.05     0.0         0.0        0   
 3          0               0     0.05     0.0         0.0        0   
 4          0               0     0.05     0.0         0.0        0   
 5          0               0     0.05     0.0         0.0        0   
 6          0               0     0.05     0.0         0.0        0   
 7          0               0     0.05     0.0         0.0        0   
 8          0               0     0.05     0.0         0.0        0   
 9          0               0     0.05     0.0         0.0        0   
 10         0               0     0.05     0.0         0.0        0   

     IR_repd_cum  IR_rsdl  fee_amt  fee_repd  fee_unpd  
-1             0      0.0      0.0         0       0.0  
 0             0      0.0      0.0         0       0.0  
 1             0      0.0      0.0         0       0.0  
 2             0      0.0      0.0         0       0.0  
 3             0      0.0      0.0         0       0.0  
 4             0      0.0      0.0         0       0.0  
 5             0      0.0      0.0         0       0.0  
 6             0      0.0      0.0         0       0.0  
 7             0      0.0      0.0         0       0.0  
 8             0      0.0      0.0         0       0.0  
 9             0      0.0      0.0         0       0.0  
 10            0      0.0      0.0         0       0.0

In [53]:
TrA.amt_pay(1, 500000)

In [54]:
TrA.df

amt_ntnl  amt_paid  amt_paid_cum  amt_paid_rsdl  amt_repd  amt_repd_cum  \
-1   10000000         0             0       10000000         0             0   
 0   10000000         0             0       10000000         0             0   
 1   10000000    500000        500000        9500000         0             0   
 2   10000000         0        500000        9500000         0             0   
 3   10000000         0        500000        9500000         0             0   
 4   10000000         0        500000        9500000         0             0   
 5   10000000         0        500000        9500000         0             0   
 6   10000000         0        500000        9500000         0             0   
 7   10000000         0        500000        9500000         0             0   
 8   10000000         0        500000        9500000         0             0   
 9   10000000         0        500000        9500000         0             0   
 10  10000000         0        500000        9500000         0             0   

     amt_rsdl  amt_paid_forIR  IR_rate       IR_amt    IR_amt_cum  IR_repd  \
-1          0               0     0.05     0.000000      0.000000        0   
 0          0               0     0.05     0.000000      0.000000        0   
 1     500000               0     0.05     0.000000      0.000000        0   
 2     500000          500000     0.05  2083.333333   2083.333333        0   
 3     500000          500000     0.05  2083.333333   4166.666667        0   
 4     500000          500000     0.05  2083.333333   6250.000000        0   
 5     500000          500000     0.05  2083.333333   8333.333333        0   
 6     500000          500000     0.05  2083.333333  10416.666667        0   
 7     500000          500000     0.05  2083.333333  12500.000000        0   
 8     500000          500000     0.05  2083.333333  14583.333333        0   
 9     500000          500000     0.05  2083.333333  16666.666667        0   
 10    500000          500000     0.05  2083.333333  18750.000000        0   

     IR_repd_cum       IR_rsdl  fee_amt  fee_repd  fee_unpd  
-1             0      0.000000      0.0         0       0.0  
 0             0      0.000000      0.0         0       0.0  
 1             0      0.000000      0.0         0       0.0  
 2             0   2083.333333      0.0         0       0.0  
 3             0   4166.666667      0.0         0       0.0  
 4             0   6250.000000      0.0         0       0.0  
 5             0   8333.333333      0.0         0       0.0  
 6             0  10416.666667      0.0         0       0.0  
 7             0  12500.000000      0.0         0       0.0  
 8             0  14583.333333      0.0         0       0.0  
 9             0  16666.666667      0.0         0       0.0  
 10            0  18750.000000      0.0         0       0.0

In [57]:
a = True

In [58]:
if a is True:
    print('a')

a


In [61]:
print("ltv : {}".format(650 / 894))
print("IR : {}".format(0.049))

ltv : 0.727069351230425
IR : 0.049


In [62]:
print("ltv : {}".format(500/890))
print("IR : {}".format(0.04))

ltv : 0.5617977528089888
IR : 0.04


In [63]:
TrA = {'amt': 360, 'IR'}

356.0

In [69]:
loan = pd.DataFrame({'amt':[360, 140], 'IR':[0.032, 0.05]}, index=['TrA', 'TrB'])
(loan.amt * loan.IR).sum() / loan.amt.sum()

0.03704

In [72]:
loan = pd.DataFrame({'amt':[300, 200], 'IR':[0.032, 0.052]}, index=['TrA', 'TrB'])
(loan.amt * loan.IR).sum() / loan.amt.sum()

0.04